<?php
namespace ShinyRobot\Log\Parser;
use ShinyRobot\Log\Message;

/**
 * Test class for j3_Log_Parser_Result.
 * Generated by PHPUnit on 2010-02-02 at 12:09:04.
 */
class ResultTest extends \PHPUnit_Framework_TestCase
{
    public function testSortByCount()
    {
        $filePath = realpath(dirname(__FILE__) . '/_files/error.log');
        $parser = AbstractParser::createErrorLogParser($filePath);
        $result = $parser->parse();
        $messages = $result->sortByCount()->getMessages();
        
        $count = count($messages);
        for ( $i = 1; $i < $count; $i++ ) {
            $this->assertGreaterThanOrEqual($messages[$i]->getCount(), $messages[$i-1]->getCount());
        }
    }

    public function testCount()
    {
        $result = new Result('', '', array());
        $this->assertEquals(0, $result->count());

        $result = new Result('', '', array(
            new Message(array('key' => 1)),
            new Message(array('key' => 2)),
            new Message(array('key' => 3)),
        ));
        $this->assertEquals(3, $result->count());
    }

    public function testInvalidMessageThrowsEception()
    {
        $this->setExpectedException('InvalidArgumentException');
        new Result('', '', array(new \StdClass()));
    }
}
